Added fastboot check
trmcnvn/ember-star-rating pull request #11
Opened 2018-03-04 08:49 UTC by alexmasita

2018-03-05 16:00 UTC, trmcnvn requested changes

2018-03-05 16:00 UTC, vevix commented on addon/components/star-rating.js
> +  fastboot: Ember.computed(function () {
Use the imported `computed` here.

```js
fastboot: computed(...)
```

2018-03-13 15:19 UTC, alexmasita commented
Done.  Let me know if okay.

2018-03-14 05:50 UTC, trmcnvn approved these changes

2018-03-14 05:51 UTC, merged